"""Adding distances to route solution

Revision ID: 0f69ab559cc5
Revises: c19f0b786faa
Create Date: 2025-08-22 17:24:24.796175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f69ab559cc5'
down_revision = 'c19f0b786faa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route_solution', schema=None) as batch_op:
        batch_op.add_column(sa.Column('legs_meters_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('total_distance_meters', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route_solution', schema=None) as batch_op:
        batch_op.drop_column('total_distance_meters')
        batch_op.drop_column('legs_meters_json')

    # ### end Alembic commands ###
