"""Added legs_json to RouteSolution.

Revision ID: 11ecb2624d10
Revises: 3166d33312ce
Create Date: 2025-07-19 16:34:51.000899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11ecb2624d10'
down_revision = '3166d33312ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route_solution', schema=None) as batch_op:
        batch_op.add_column(sa.Column('legs_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route_solution', schema=None) as batch_op:
        batch_op.drop_column('legs_json')

    # ### end Alembic commands ###
