"""Added a new table for capturing ratings.

Revision ID: 1f0c0a3817cf
Revises: 85fb86d19170
Create Date: 2025-07-10 20:24:58.255307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f0c0a3817cf'
down_revision = '85fb86d19170'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=8), nullable=False),
    sa.Column('rating', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.String(length=400), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_rating')
    # ### end Alembic commands ###
