"""Added new column to the pickup_requests table.

Revision ID: 3166d33312ce
Revises: 1f0c0a3817cf
Create Date: 2025-07-19 14:36:58.810671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3166d33312ce'
down_revision = '1f0c0a3817cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pickup_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('geocoded_addr', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pickup_requests', schema=None) as batch_op:
        batch_op.drop_column('geocoded_addr')

    # ### end Alembic commands ###
