"""Add address2 column to pickup_requests

Revision ID: 85fb86d19170
Revises: 7031c750ed03
Create Date: 2025-07-05 12:07:24.916092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85fb86d19170'
down_revision = '7031c750ed03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pickup_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address2', sa.String(length=200), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pickup_requests', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.drop_column('address2')

    # ### end Alembic commands ###
