"""Adding the MOPF table.

Revision ID: 86c4732d7fc3
Revises: 0f69ab559cc5
Create Date: 2025-09-18 18:28:26.325372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86c4732d7fc3'
down_revision = '0f69ab559cc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donation_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=50), nullable=True),
    sa.Column('lastName', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('secondaryAddress', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('zip', sa.String(length=10), nullable=False),
    sa.Column('estimated_value', sa.String(length=5), nullable=False),
    sa.Column('donation_date', sa.String(length=20), nullable=False),
    sa.Column('date_filed', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('donation_records')
    # ### end Alembic commands ###
