"""Add request_id and phone_number columns

Revision ID: 8c176f24fae0
Revises: 
Create Date: 2025-02-27 19:16:52.486749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c176f24fae0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pickup_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_id', sa.String(length=6), nullable=False))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint(None, ['request_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pickup_requests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('request_id')

    # ### end Alembic commands ###
